spring:
  datasource:
    url: jdbc:h2:./data/sample;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
logging:
  level:
    ROOT: debug
#security:
#  oauth2:
#    resource:
#      filter-order: 3